Aait.web.g2.kaleabe negussie.success stories review added success stories page and footer
RealEskalate/2023-project-phase-starter-projects pull request #159
Opened 2023-08-24 07:37 UTC by kaleabe-n

![Screenshot 2023-08-24 102821](https://github.com/RealEskalate/2023-project-phase-starter-projects/assets/91533360/9f10ab2b-ca10-416e-873a-11e4f076fbd0)
![Screenshot 2023-08-24 102813](https://github.com/RealEskalate/2023-project-phase-starter-projects/assets/91533360/d4599480-4e27-4019-a3d2-744b72f93994)
![Screenshot 2023-08-24 102805](https://github.com/RealEskalate/2023-project-phase-starter-projects/assets/91533360/f90912fe-68d6-4e90-af5f-10e6753ea9cb)
![Screenshot 2023-08-24 102755](https://github.com/RealEskalate/2023-project-phase-starter-projects/assets/91533360/178441d0-b267-4023-97a3-b188490
![Screenshot 2023-08-24 102711](https://github.com/RealEskalate/2023-project-phase-starter-projects/assets/91533360/65016d44-6de1-4c9e-89c9-ad33c989c210)
6e2bf)

2023-08-24 07:54 UTC, FevenBelay23 requested changes

2023-08-24 07:54 UTC, FevenBelay23 commented on aait/web/group-2/components/footer/index.tsx
use PascalCase naming for components

2023-08-24 07:54 UTC, FevenBelay23 commented on aait/web/group-2/public/images/Google.png
use kebab-case  naming style for all files and folders other than components.

2023-08-24 07:54 UTC, FevenBelay23 commented on aait/web/group-2/app/success-stories/page.tsx
> +    return ( <main className="">
use the extension prettier to make your code properly structured.

2023-08-24 13:03 UTC, Aklile-Yilma commented on aait/web/group-2/app/success-stories/page.tsx
> +      {isSuccess && !isError && (
IsSuccess tells you if its successful why use isError to?

2023-08-24 13:23 UTC, Aklile-Yilma commented on aait/web/group-2/components/footer/Footer.tsx
> +            <li className="mb-2">Advisors</li>
You can take this out to a json object and map through it to get this ui

2023-08-24 13:25 UTC, Aklile-Yilma commented on aait/web/group-2/components/single-success-story/SingleSuccessStory.tsx
> +            return (
You can remove the return statement by replacing the curly brace with brackets

2023-08-28 06:59 UTC, Aklile-Yilma approved these changes
LGTM

2023-08-28 07:29 UTC, FevenBelay23 approved these changes

2023-08-28 07:29 UTC, FevenBelay23 approved these changes

2023-08-28 08:21 UTC, zelalemyetsedaw approved these changes

2023-08-28 08:22 UTC, merged

2023-08-28 08:22 UTC, FevenBelay23 approved these changes