fix(AAiT-Backend-2B): Add more test cases to cover other scenarios
RealEskalate/2023-project-phase-starter-projects pull request #396
Opened 2023-08-29 11:53 UTC by ffekirnew

2023-08-29 13:36 UTC, Geleta116 approved these changes
LGTM.

2023-08-29 16:58 UTC, abrahamshimekt commented on aait/backend/group-2B/Application.Tests/Features/Authentication/Handlers/Commands/RegisterUserCommandHandlerTest.cs
> +        newUser.Username = "new_username";
This line may be unnecessary. you can create the new user with userName ="new_user"

2023-08-29 17:12 UTC, abrahamshimekt commented on aait/backend/group-2B/Application.Tests/Features/Authentication/Handlers/Commands/RegisterUserCommandHandlerTest.cs
> +
You don't need to call the handler twice . You can use the user in the user mockreposiotry

2023-08-29 17:20 UTC, abrahamshimekt commented on aait/backend/group-2B/Application.Tests/Features/Authentication/Handlers/Queries/LoginUserRequestHandlerTest.cs
> +    public async Task Invalid_InvalidUsernameLogin()
This test must be testing against non existent username instead of saying invalid username. Because the username is valid but it may not exist.

2023-08-29 17:24 UTC, abrahamshimekt requested changes
address the issues given if they are feasible according to your need.

2023-08-30 12:14 UTC, abrahamshimekt approved these changes

2023-08-30 12:21 UTC, merged