feat(AAiT-bac-g2a): test feature
RealEskalate/2023-project-phase-starter-projects pull request #439
Opened 2023-08-30 06:57 UTC by Dagm-M

2023-08-30 11:27 UTC, abrahamshimekt requested changes

2023-08-30 11:27 UTC, abrahamshimekt commented on aait/backend/group-2A/Application.Tests/Post/Commands/CreatePostCommandHandlerTests.cs
> +﻿using Application.Contracts.Persistance;
add tests for creating posts when the createpostdto has invalid data

2023-08-30 11:27 UTC, abrahamshimekt commented on aait/backend/group-2A/Application.Tests/Mocks/MockPostRepository.cs
> +                          });
Mock the save method too.

2023-08-30 11:27 UTC, abrahamshimekt commented on aait/backend/group-2A/Application.Tests/Like/Commands/DeleteLikeCommandHandlerTests.cs
> +            var handler = new DeleteLikeCommandHandler(_mockRepo.Object, _mapper);
you can avoid the calling the getLikedPost method by tracking a changing in the unit of work mock repository

2023-08-30 11:27 UTC, abrahamshimekt commented on aait/backend/group-2A/Application.Tests/Follow/Commands/DeleteFollowCommandHandlerTests.cs
> +            var handler = new DeleteFollowCommandHandler(_mockRepo.Object, _mapper);
move this to the constructor

2023-08-30 20:38 UTC, Dagm-M commented on aait/backend/group-2A/Application.Tests/Post/Commands/DeletePostCommandHandlerTests.cs
> +            var updatedPostList = await _mockRepo.Object.postRepository.GetAll();
I didn't understand

2023-08-31 06:27 UTC, abrahamshimekt approved these changes
looks fine to me

2023-08-31 06:27 UTC, merged